### PR TITLE
Revert "Rename folder for strings"

### PR DESCRIPTION
**Pull request by tmolitor-stud-tu**
This reverts commit 2b97087643a62e0a332f1a9d50b1e74e9c4d31f1.

### CODE REVIEW

**Comment by Echolon** [comment]
Why revert? It was requested by Weblate?

**Comment by tmolitor-stud-tu** [comment]
I'm currently configuring weblate and it showed a strange error having base and en directories, but I think I solved this...this can be closed maybe...

**Comment by Echolon** [comment]
Ok cool

**Comment by tmolitor-stud-tu** [comment]
yes, please merge this

**Pull request merged**
