### PR TITLE
Pr04

### PR DESCRIPTION
**Pull request by tmolitor-stud-tu**
Fix some important bugs in current beta

### CODE REVIEW

**Comment by tmolitor-stud-tu** [comment]
I removed 2 commits as you requested

**Comment by anurodhp** [comment]
last commit doesnt build

**Comment by tmolitor-stud-tu** [comment]
yeah, but that's a travis problem, it builds just fine here

**Comment by tmolitor-stud-tu** [comment]
Sure

Am 22. Juli 2020 08:58:59 MESZ schrieb Friedrich Altheide <notifications@github.com>:

**Comment by tmolitor-stud-tu** [comment]
approved :)

**Pull request merged**
