### PR TITLE
Fix connection problems and some cleanup

### PR DESCRIPTION
**Pull request by tmolitor-stud-tu**
This fixes some connection problems and does some code cleanup

### CODE REVIEW

**Comment by anurodhp** [comment]
please squash to a single commit. it makes review a lot easier

**Comment by Echolon** [comment]
Any relation to issues?

**Comment by tmolitor-stud-tu** [comment]
But it will make the history way more unreadable and you won't be able to do a git blame or other history related things...

I can see if I can squash some related commits, but squashing *all* commits together, even unrelated ones, will make the got commit history unreadable.

Am 23. Mai 2020 17:00:32 MESZ schrieb Anu Pokharel <notifications@github.com>:

**Comment by anurodhp** [comment]
Related is good.

**Comment by tmolitor-stud-tu** [comment]
What tool are you using for the review?

In github you can use this to see all changes at once: https://github.com/anurodhp/Monal/pull/409/files

**Comment by tmolitor-stud-tu** [comment]
The official git documentation says this about squashing/non-squashing of logically distinct commits:

> try to make each commit a logically separate changeset. If you can, try to make your changes digestible — don’t code for a whole weekend on five different issues and then submit them all as one massive commit on Monday. [...]

https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

**Comment by anurodhp** [comment]
I use GitHub. If you squash  it by issue it would be good esp if you have commit fixing errors in earlier Commits

**Comment by tmolitor-stud-tu** [comment]
well, squashing should not matter then because github already allows reviewing all changes at once.

as for the issues: I'm not aware of any related github issues.
@friedrichaltheide and I fixed errors we encountered in our own local tests on several devices an in the simulator.

**Comment by tmolitor-stud-tu** [comment]
okay...squashing failed...now everything is broken...great...

**Comment by tmolitor-stud-tu** [comment]
this time it worked as expected, ready to be merged.

side node: @FriedrichAltheide and I are planning to rework the notification system and make it work for ios 13 again...we will start working on this in about 2 weeks.

**Comment by anurodhp** [comment]
Great, I’ll look when I have time. For the notification system, hold on and coordinate with me. 90% of it is done. Last bit is a security setting

**Comment by tmolitor-stud-tu** [comment]
great news! any branch where I can see your work on this?

**Pull request merged**
