### PR TITLE
List known server software by popularity

### PR DESCRIPTION
**Pull request by licaon-kter**
Ref: https://twitter.com/iNPUTmice/status/1257543944486785030

### CODE REVIEW

**Comment by tmolitor-stud-tu** [comment]
this one will change nothing as long as the string is not changed in the code, too!!!

**Comment by licaon-kter** [comment]
@tmolitor-stud-tu ....do explain though

**Comment by anurodhp** [comment]
Oh ha I just noticed the key changed too ans  the string 

--
Anurodh Pokharel

**Comment by Echolon** [comment]
@licaon-kter the string file is just an export from xcode of all the strings placed in the actual code. You actually should find the string in the Monal code and change it there. Then Thilo can export and merge a new Localizations.string file

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter the left side of the strings file is actually no arbitrary string, but an ID.
This ID has to equal the string used in the code/storyboard.
If you change the ID in the strings file the app won't find it and use the string from code instead (or an empty string, I don't know exactly).

**Pull request merged**
