### PR TITLE
Pr05

### PR DESCRIPTION
**Pull request by tmolitor-stud-tu**

### CODE REVIEW

**Comment by anurodhp** [comment]
this is a huge commit. ill try my best to review it but minus any glaring issues we may just merge this in a day or so.  you should resolve the strings conflict,

**Comment by Echolon** [comment]
Yes, I know and see it was a lot work into this and is good it was done. However, I think:

- The title should at least summarize the biggest changes
- And it should be separated into several PRs, I think this is easier for Anu to review and but will increase quality even if we risk it takes longer till merged.

I mean you have you alpha where you can build at the moment anyway.

**Comment by tmolitor-stud-tu** [comment]
@Echolon this PR can't be split in any meaningful way because push won't work if split.

**Comment by tmolitor-stud-tu** [comment]
@anurodhp the strings conflict should be resolved now :)

**Comment by anurodhp** [comment]
please resolve the conflicts.

**Pull request merged**
